name: contact_bloc
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  freezed: ^1.1.1
  
  build_runner: ^2.1.8
  
  flutter_lints: ^4.0.0

flutter:
  
  uses-material-design: true
